site_name: Fixed Point Maths
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Utilities: utilities.md
  - Q-Type: q.md
  - Sq-Type: sq.md
theme: readthedocs

use_directory_urls: false

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
